# Use the official Ubuntu base image
FROM ubuntu:latest

# Set the working directory in the container
WORKDIR /app

# Update the package lists and install essential dependencies
RUN apt-get update && \
    apt-get install -y python3.11 python3-pip

# Copy the requirements.txt file into the container at /app
COPY requirements.txt /app/
COPY producer.py /app/

# Install the Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app/

# Set the environment variable for Python to use UTF-8 encoding
ENV PYTHONIOENCODING=utf-8

# Run consumer.py when the container launches
CMD ["python3", "producer.py"]